<?php

/* Generated automagically, see WHINE/Apps/Vault-Tec DB/Web Engine/www/i/vtdb-lang */

# FOGAME.MSG :: 400 - 406
$lang_special_short = array(
	"ST",
	"PE",
	"EN",
	"CH",
	"IN",
	"AG",
	"LK"
);

# FOGAME.MSG :: 100001 - 100061 (step 10)
$lang_special_long = array(
	"Strength",
	"Perception",
	"Endurance",
	"Charisma",
	"Intelligence",
	"Agility",
	"Luck"
);

# FOGAME.MSG :: 100002 - 100062 (step 10)
$lang_special_long_descr = array(
	"Raw physical strength. A high Strength is good for physical characters. Modifies: Hit Points, Melee Damage, and Carry Weight.",
	"The ability to see, hear, taste and notice unusual things. A high Perception is important for a sharpshooter.  Modifies: Sequence and ranged combat distance modifiers.",
	"Stamina and physical toughness. A character with a high Endurance will survive where others may not. Modifies: Hit Points, Poison & Radiation Resistance, Healing Rate, and the additional hit points per level.",
	"A combination of appearance and charm. A high Charisma is important for characters that want to influence people with words. Modifies: NPC reactions, and barter prices.",
	"Knowledge, wisdom and the ability to think quickly. A high Intelligence is important for any character. Modifies: the number of new skill points per level, dialogue options, and many skills.",
	"Coordination and the ability to move well. A high Agility is important for any active character. Modifies: Action Points, Armor Class, and many skills.",
	"Fate. Karma. An extremely high or low Luck will affect the character - somehow. Events and situations will be changed by how lucky (or unlucky) your character is."
);

# FOGAME.MSG :: 2301 - 2310
$lang_special_rating = array(
	"V. Bad",
	"Bad",
	"Poor",
	"Fair",
	"Average",
	"Good",
	"V. Good",
	"Great",
	"Excellent",
	"Heroic"
);

# FOGAME.MSG :: 4113 - 4115
$lang_xp = array(
	"Level: %d",
	"Exp: %d",
	"Next Level: %d"
);

# FOGAME.MSG :: 4053 - 4054, 4051
$lang_xp_descr = array(
	"The general competency of the player character. A measure of your experience and abilities.",
	"A reward for completing specific tasks, or defeating enemies in combat. More experience points are required to attain higher Levels.",
	"The amount of experience points needed to move up to the next level."
);

# FOGAME.MSG :: 407, 443 - 444, 105021 - 105061 (step 10)
$lang_life = array(
	"Hit Points",
	"Poisoned",
	"Radiated",
	"Eye Damage",
	"Crippled Right Arm",
	"Crippled Left Arm",
	"Crippled Right Leg",
	"Crippled Left Leg"
);

# FOGAME.MSG :: 100072, 105002 - 105062 (step 10)
$lang_life_descr = array(
	"How much damage your character can take before dying.",
	"Your character has been poisoned.  Poison will do damage over a period of time, until cured or it passes from your system.",
	"Your character is suffering from a significant amount of Radiation poisoning.  The more radiation damage, the more deadly the effect.",
	"This means your character has been seriously hit in one or both of your eyes.  This affects your Perception.",
	"The right arm has been severely hurt, and cannot function well.  If one arm has been crippled, you cannot use two-handed weapons.  If both arms have been crippled, you cannot attack with weapons.",
	"Your character\'s left arm has been severely hurt, and cannot function well.  If one arm has been crippled, you cannot use two-handed weapons.  If both arms have been crippled, you cannot attack with weapons.",
	"Your character has a crippled right leg.",
	"Your character has a crippled left leg."
);

# FOGAME.MSG :: 100093, 100083, 100113, 100103, 100233, 100313, 100303, 100123, 100133, 100143
$lang_stats = array(
	"Armor Class",
	"Action points",
	"Carry Weight",
	"Melee Damage",
	"Damage Res.",
	"Poison Res.",
	"Radiation Res.",
	"Sequence",
	"Healing Rate",
	"Critical Chance"
);

# FOGAME.MSG :: 100092, 100082, 100112, 100102, 100232, 100312, 100302, 100122, 100132, 100142
$lang_stats_descr = array(
	"Modifies the chance to hit this particular character.",
	"The number of actions that the character can take during one combat turn.",
	"The maximum amount of equipment your character can carry, in pounds.",
	"The amount of bonus damage your character does in hand-to-hand combat.",
	"Any damage taken is reduced by this amount. Damage Resistance can be increased by wearing armor.",
	"Reduces poison damage by this amount.",
	"The amount of radiation you are exposed to is reduced by this percentage. Radiation Resistance can be modified by the type of armor worn, and anti-radiation chems.",
	"Determines how soon in a combat turn your character can react.",
	"At the end of each day, your character will heal 1 HP for each point of Healing Rate.  When you rest, you heal every six hours.",
	"The chance to cause a critical hit in combat is increased by this amount."
);

# FOGAME.MSG :: 102001 - 102171 (step 10)
$lang_skills = array(
	"Small Guns",
	"Big Guns",
	"Energy Weapons",
	"Close Combat",
	"Evading",
	"Throwing",
	"First aid",
	"Doctor",
	"Sneak",
	"Lockpick",
	"Steal",
	"Traps",
	"Science",
	"Repair",
	"Speech",
	"Barter",
	"Gambling",
	"Outdoorsman"
);

# FOGAME.MSG :: 102002, 102012, 102022, 102032, 102042, 102052, 102062, 102072, 102082, 102092, 102102, 102112, 102122, 102132, 102142, 102152, 102162, 102172
$lang_skills_descr = array(
	"The use, care and general knowledge of small firearms - pistols, SMGs and rifles.",
	"The operation and maintenance of really big guns - miniguns, rocket launchers, flamethrowers and such.",
	"The care and feeding of energy-based weapons.  How to arm and operate weapons that use laser or plasma technology.",
	"A combination of martial arts, non-ranged weapons in hand-to-hand, or melee combat - knives, sledgehammers, spears, clubs and so on.",
	"Ability to make moves to avoid or block an incoming attack.",
	"The skill of muscle-propelled ranged weapons, such as throwing knives, spears and grenades.",
	"General healing skill.  Used to heal small cuts, abrasions and other minor ills.  In game terms, the use of first aid can heal more hit points over time than just rest.",
	"The healing of major wounds and crippled limbs.  Without this skill, it will take a much longer period of time to restore crippled limbs to use.",
	"Quiet movement, and the ability to remain unnoticed. If successful, you will be much harder to locate. You cannot run and sneak at the same time.",
	"The skill of opening locks without the proper key. The use of lock picks or electronic lock picks will greatly enhance this skill.",
	"The ability to make the things of others your own.  Can be used to steal from people or places.",
	"The finding and removal of traps.  Also the setting of explosives for demolition purposes.",
	"Covers a variety of high technology skills, such as computers, biology, physics and geology.",
	"The practical application of the Science skill for fixing broken equipment, machinery and electronics.",
	"The ability to communicate in a practical and efficient manner. The skill of convincing others that your position is correct. The ability to lie and not get caught.",
	"Trading and trade-related tasks. The ability to get better prices for items you sell, and lower prices for items you buy.",
	"The knowledge and practical skills related to wagering. The skill at cards, dice and other games.",
	"Practical knowledge of the outdoors, and the ability to live off the land. The knowledge of plants and animals."
);

# FOGAME.MSG :: 4057, 4056, 4058
$lang_tabs_descr = array(
	"Perks add additional abilities. Every third experience level, you can choose one perk.",
	"These are the effects of the choices you make during the game.",
	"A counter that keeps track of the type and numbers of creatures you have slaughtered, or have seen killed in your presence."
);

# FOGAME.MSG :: 4011, 105501 - 105661 (step 10)
$lang_traits = array(
	"Traits",
	"Fast Metabolism",
	"Bruiser",
	"Small Frame",
	"One Hander",
	"Finesse",
	"Kamikaze",
	"Heavy Handed",
	"Fast Shot",
	"Bloody Mess",
	"Jinxed",
	"Good Natured",
	"Chem Reliant",
	"Chem Resistant",
	"Bonehead",
	"Skilled",
	"Loner",
	"Gifted",
	"Member of New California Republic",
	"Member of Brotherhood of Steel",
	"Member of Vault City",
	"Member of Enclave"
);



# FOGAME.MSG :: 4061, 105502 - 105662 (step 10)
$lang_traits_descr = array(
	"Optional traits describe your character in more detail.  All traits will have positive and negative effects.  You may choose up to two traits during creation.",
	"Your metabolic rate is twice normal.  This means that effects of drugs and medicines wear off twice as fast, but your body heals faster.",
	"A little slower, but a little bigger.  You may not hit as often, but they will feel it when you do!  Your total action points are lowered, but your Strength is increased and you deal even more damage in melee.",
	"You are not quite as big as the other ordinary man, but that never slowed you down.  You can't carry as much, but you are more agile.",
	"One of your hands is very dominant.  You excel with single-handed weapons, but two-handed weapons cause a problem.",
	"Your attacks show a lot of finesse.  You don't do as much damage, but you cause more critical hits.",
	"By not paying attention to any threats, you can act a lot faster in a turn.  This lowers your damage resistance, but increases armor class.",
	"You swing harder, not better.  Your attacks are very brutal, but lack finesse.  You rarely cause a good critical, but you always do more unarmed damage. Additionally, all your close combat attacks knock down the opponent if a successful Strength roll was made.",
	"You don't have time to aim for a targeted attack, because you attack faster than normal people.  It costs you one less action point for guns and thrown weapons, and then one less with two handed weapons.",
	"By some strange twist of fate, people around you die violently.  You always see the worst way a person can die.",
	"The good thing is that everyone around you has more critical failures in combat, the bad thing is so do you!",
	"There is a positive aura about you. People are more likely to follow you, but you can't own any slaves.",
	"You are more easily addicted to chems.  All drug addictions are permanent, but the drug effects last twice as long.",
	"You are immune to drug addiction effects, but regain only half the normal hit points while using medicines.",
	"A thicker than average cranium means you can shrug off hits to the head that would floor others.  Unfortunatly that doesn't leave much room up there.",
	"Since you spent more time improving your skills than a normal person, you gain 5 additional skill points per experience level. The tradeoff is that you do not gain as many extra abilities. You gain a perk every four levels.",
	"You appreciate the nature more than company of others. You gain 10% more experience, but you can't have any followers.",
	"You have more innate abilities than most, so you have not spent as much time honing your skills.  Your primary statistics are each +1, but you lose -10% on all skills to start, and receive 5 less skill points per level.",
	"You have been instructed in some areas, but if you leave this faction you will be not liked by people from it anymore and even confession will not help. You also can't join another political faction.",
	"You have been instructed in some areas, but if you leave this faction you will be not liked by people from it anymore and even confession will not help. You also can't join another political faction.",
	"You have been instructed in some areas, but if you leave this faction you will be not liked by people from it anymore and even confession will not help. You also can't join another political faction."
);

# FOGAME.MSG :: 4007, 103001 - 103631 (step 10), 103801 - 104081 (step 10), 104171, 104191 - 104691 (step 10)
$lang_perks = array(
	"Perks",
	"Bookworm",
	"Awareness",
	"Bonus HtH Attacks",
	"Bonus HtH Damage",
	"Bonus Move",
	"Bonus Ranged Damage",
	"Bonus Rate of Fire",
	"Earlier Sequence",
	"Faster Healing",
	"More Critical",
	"Night Vision",
	"Presence",
	"Rad Resistance",
	"Toughness",
	"Strong Back",
	"Sharpshooter",
	"Silent Running",
	"Survivalist",
	"Master Trader",
	"Educated",
	"Healer",
	"Fortune Finder",
	"Better Critical",
	"Empathy",
	"Slayer",
	"Sniper",
	"Silent Death",
	"Action Boy",
	"Mental Block",
	"Lifegiver",
	"Dodger",
	"Snakeater",
	"Mr. Fixit",
	"Medic",
	"Master Thief",
	"Speaker",
	"Heave Ho!",
	"Friendly Foe",
	"Pickpocket",
	"Ghost",
	"Cult of Personality",
	"Scrounger",
	"Explorer",
	"Flower Child",
	"Pathfinder",
	"Animal Friend",
	"Scout",
	"Mysterious Stranger",
	"Ranger",
	"Quick Pockets",
	"Smooth Talker",
	"Swift Learner",
	"Tag!",
	"Mutate!",
	"Profession: Armorer",
	"Profession: Gunsmith (Small Guns)",
	"Profession: Gunsmith (Big Guns)",
	"Profession: Energy Expert",
	"Profession: Demolition Expert",
	"Profession: Doctor",
	"Profession: Bartender",
	"Profession: Ironmaster",
	"Profession: Ironworker",
	"Profession: Scout",
	"Adrenaline Rush",
	"Cautious Nature",
	"Comprehension",
	"Demolition Expert",
	"Gambler",
	"Gain Strength",
	"Gain Perception",
	"Gain Endurance",
	"Gain Charisma",
	"Gain Intelligence",
	"Gain Agility",
	"Gain Luck",
	"Harmless",
	"Here and Now",
	"HtH Evade",
	"Kama Sutra Master",
	"Karma Beacon",
	"Light Step",
	"Living Anatomy",
	"Magnetic Personality",
	"Negotiator",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	"Pack Rat",
	"Pyromaniac",
	"Quick Recovery",
	"Salesman",
	"Stonewall",
	"Thief",
	"Weapon Handling",
	"Vault City Training",
	"Expert Excrement Expeditor",
	"Jinxed",
	"Terminator",
	"Tree Trunk Thighs",
	"Iron Grip",
	"Man of Steel",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	"Even More Criticals",
	"Right Between the Eyes",
	"Fast Reload",
	"Spray and Pray",
	"More Ranged Damage",
	"Livewire",
	"Gecko Skinning",
	"Vault City Inoculations",
	"Implant: Dermal Impact Armor",
	"Implant: Dermal Impact Assault Enhancement",
	"Implant: Phoenix Armor Implants",
	"Implant: Phoenix Assault Enhancement",
	"HtH Evade+",
	"Dodger+",
	"Even Tougher",
	"Healer+",
	"Blessed are the Weak",
	"Night Person",
	"Melt Into Shadow",
	"More HtH Criticals",
	"In Your Face!",
	"Hit the Gaps",
	"Better HtH Criticals",
	"Heave Ho!!",
	"Junk Merchant",
	"Bulk Trader",
	"Sex Appeal",
	"Born Leader",
	"Trapper",
	"Hand Loader",
	"Stealth Girl",
	"Best of a Bad Lot",
	"Dismantler",
	"Vigilant Recycler",
	"Retention",
	"Treasure Hunter",
	"reserved",
	"Dead Man Walking",
	"Implant: Nemean Armor",
	"Implant: Hypertrophy Accelerator",
	"Implant: Optics Enhancer",
	"Implant: Nociception Regulator",
	"Implant: Empathy Synthesizer",
	"Implant: Logic Co-processor",
	"Implant: Reflex Booster",
	"Implant: Probability Calculator"
);

	
	
	

# FOGAME.MSG :: 4057, 103002 - 103632 (step 10), 103802 - 104082 (step 10), 104172, 104192 - 104692 (step 10)
$lang_perks_descr = array(
	"Perks add additional abilities. Every third experience level, you can choose one perk.",
	"Bookworm.",
	"With Awareness, you are given detailed information about any critter you examine.  You see their exact hit points and information about any weapon they are equipped with.",
	"You have learned the secret arts of the East, or you just punch faster.  In any case, your Hand-to-Hand attacks cost 1 AP less to perform.",
	"Experience in unarmed combat has given you the edge when it comes to damage.  You cause +7 points of damage with hand-to-hand and melee attacks.",
	"{For each level of Bonus Move, you get 2 free APs each turn that can only be used for movement.  In other words, you can move 2 free hexes each turn for each level of this Perk.",
	"Your training in firearms and other ranged weapons has made you more deadly in ranged combat.  For each level of this Perk, you do +2 points of damage with ranged weapons.",
	"This Perk allows you to pull the trigger a little faster and still remain as accurate as before.  Each ranged weapon attack costs 1 AP less to perform.",
	"You are more likely to move before your opponents in combat, since your Sequence is increased by +2 points.",
	"With this Perk, you get a +5 bonus to your Healing Rate. This is in addition to your normal healing rate, thus you heal faster.",
	"You are more likely to cause critical hits in combat if you have this Perk. You get an additional +5% chance to cause a critical hit.",
	"With the Night Vision Perk, you can see in the dark better.  This will reduce the overall darkness level by 20%.",
	"You command attention by just walking into a room.  The initial reaction of another person is improved by 10% for each level of this Perk.",
	"You are able to avoid radiation and its bad effects more effectively.  Each level of this Perk improves your Radiation Resistance by 30% and your Poison Resistance by 20%.",
	"When you are tough, you take less damage. You gain +5% to your general damage resistance and +2 to your general damage threshold.",
	"AKA Mule. You can carry an additional 22 kg of equipment.",
	"You have a talent for hitting things at longer distances.  For each level of this Perk, you get a +2 bonus to Perception for the purposes of determining sight range.  You also get a small bonus to chance to hit your opponent with ranged weapon.",
	"With this Perk, you now have the ability to move quickly and still remain quiet.  You can Sneak and run without suffering any penalty.  ",
	"You are a master of the outdoors.  When you kill animals, you are able to take double the amount of meat from them.",
	"You have mastered one aspect of bartering - buying goods far more cheaply than normal. With this Perk, you get a 25% discount when purchasing items from a store or another trader.",
	"Each level of Educated adds +2 skill points when you gain a new experience level. This Perk works best when purchased early in your adventure.",
	"The healing of bodies comes easier to you with this Perk. This Perk heals 15-30 additional hit points when using the First Aid.",
	"You have the talent of finding money. You find additional money in random encounters in the desert.",
	"The critical hits you cause in ranged combat are more devastating. You gain a +20 bonus on the critical hit table, almost ensuring that more damage will be done. This does not affect the chance to cause a critical hit.",
	"You have studied other human beings, giving you inside knowledge of their emotional reaction to you.  You will see the reaction level of the person you are talking to when involved in an in-depth conversation.",
	"The Slayer walks the earth!  In hand-to-hand combat all of your hits are upgraded to critical hits, causing destruction and mayhem.",
	"You have mastered the firearm as a source of pain.  With this Perk, any successful hit in combat with a ranged weapon will be upgraded to a critical hit if you also make a Luck roll.",
	"While Sneaking, if you hit a critter in the back, you will cause and automatic critical hit with +10 on the roll when attacking hand to hand or with a thrown or one handed weapon. Silent Death is that kind of Perk.",
	"Action Boy (insert Girl if you wish) gives you an additional 2 APs to spend every combat turn.  You can use these generic APs on any task.",
	"Mental Block is the ability to tune out any outside mental interference.  You must have learned this talent from a passing guru, or from a really late night at a bar.",
	"With each respective level of this Perk, you gain an additional 40, 30 and 20 Hit Points.  This is in addition to the hit points you already gain per level based off of your Endurance.",
	"You are less likely to be hit in combat if you have this Perk. You gain a +20 to your Armor Class.",
	"Yum! Tastes like chicken. With this Perk you gain +30% to your Poison Resistance and +20% to your Radiation Resistance.",
	"Mr Fixit is able to repair items to a higher standard than his peers. ",
	"The Medic halves the timeouts for First Aid and Doctor skills.",
	"A Master Thief is proficient at stealing and picking locks.  He is able to attempt his thievery twice as often.",
	"Being a Speaker means your follower’s loyalty decreases at half the normal rate.",
	"This perk gives you an additional +1 to Strength (up to 10), for purposes of determining range with thrown weapons only. This Perk will exceed a weapon's maximum range.",
	"Friendly Foe",
	"You are much more adept at stealing than a normal crook.  You can steal with the best of them, because with this Perk, you halve the size and facing modifiers when stealing from a person.",
	"When the sun goes down or you are in a poorly lit area, you move like a ghost with this Perk.  Your get the bonus for being near walls from 5 hexes away.",
	"Your reputation is always positive to people. Without this Perk, a large negative reputation would have a bad effect on good natured people. This works in the reverse as well. Evil people will even treat Mr. Goodie Good as one of the gang.",
	"You can find more ammo than the normal post-holocaust survivor. This Perk doubles the amount of ammo found in random encounters.",
	"The mark of the Explorer is to search out new and interesting locations.  With this Perk, you ignore half of speed penalties for terrain on the world map.",
	"With this Perk, you are less likely to be addicted to chems (50% less likely, actually), and you suffer half the withdrawal time of a normal person.",
	"The Pathfinder is able to find the shortest route available.  With this Perk, your travel speed on the World Map is increased by 15%.",
	"Animals will not attack one of their friends, unless the animal is threatened or attacked first.  Exactly what an animal is in this world is open to debate.",
	"You have improved your ability to see and recognize distant locations and events, increasing the size of explorations on the World Map by one square in each direction.",
	"With this Perk, you have gained the attention of a Mysterious Stranger, who will appear to help you from time to time.  If your ally is lost in combat, do not expect him (or her) to be replaced.",
	"Due to the extensive amount of time spend in the wilderness, you have learned to create the right items and tools necessary for survival. From now on, you will make a Safe House instead of a tent.",
	"You have learned to pack your equipment better, your increased dexterity enables you to retrieve and put away items in half the time.",
	"You have learned to increase your dialog options without understanding what you're talking about.  Each level of this Perk will increase your Intelligence by one, up to 10, for purposes of dialog only.",
	"You are indeed a Swift Learner with this Perk, as each level gives you an additional +10% bonus whenever you earn experience points.  This is best taken early.",
	"Your skills have improved to the point where you can pick an additional Tag Skill.  Tag skills increase twice as fast.",
	"The radiation of the wasteland has changed you!  One of your Traits has mutated into something else...",
	"Your everyday outfit just don't cut it. Making your personal, straight-from-the-workbench protective gear is something you live for.",
	"You feel like your life would make no sense without pistols, rifles and ammo. You use each and every chance to make something that can shoot or be shot at.",
	"You feel like your life would make no sense without big guns and ammo. You use each and every chance to make something that can make a big boom.",
	"Your life has one purpose only: to master the energy flows and storages. Good thing you can use your experience even when fiddling with the energy weapons.",
	"If it ain't go boom, it has no meaning to you. You're obsessed with explosions, really.",
	"Helping people when they are injured or ill is all you care about. Noble profession, indeed.",
	"With such talent you don't have to drink your own urine. Never more...",
	"Metals and their alloys - have them in one finger. You know how to pour them out so they are not too fragile and not too soft.",
	"You are one of those irreplaceable. Ironwork is so rare today.",
	"There's no rathole in this world you are not going to find. The question is only how much time you're going to need for that.",
	"With this Perk, you gain +5% to your Damage Resistance and +1 to Damage Threshold for each quarter of the hit points you lose.",
	"You are more alert outdoors and enemies are less likely to sneak up on you.  With this Perk you get a +3 to your perception in random encounters when determining placement.",
	"You pay much closer attention to the smaller details when reading.  You gain 50% more skill points when reading books.",
	"You are an expert when it comes to the fine art of handling explosives.  They always go off when they're supposed to and inflict some extra damage.",
	"You can roll with the best of them.  You gain +20% to your gambling skill.",
	"With this Perk you gain +1 to your Strength.",
	"With this Perk you gain +1 to your Perception.",
	"With this Perk you gain +1 to your Endurance.",
	"With this Perk you gain +1 to your Charisma.",
	"With this Perk you gain +1 to your Intelligence.",
	"With this Perk you gain +1 to your Agility.",
	"With this Perk you gain +1 to your Luck.",
	"Your innocent demeanor makes stealing from people a little easier.  You lose only half the reputation when stealing.",
	"With this Perk you immediately gain one experience level.",
	"If both item slots are empty, you get additional 20 points to your AC.",
	"When it comes to pleasing sexually, you wrote the book.",
	"Your Karma shines twice as bright. Whether good or bad, your Karma is doubled for any kind of reaction or modifiers.",
	"You are agile, lucky and always careful.  This perk halves your chances for setting off a trap.",
	"You have a better understanding of living creatures and their strengths and weaknesses.  You get more critical successes and fewer critical failures when you are healing, and you do +5 damage per attack to living creatures.",
	"People just love to be around you!  You gain additional 50 points to your follower limit.",
	"You are a notorious negotiator.  Not only can you barter with the best of them, you can also talk your way into or out of nearly anything.  With this Perk your worst reputation counts as neutral.",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	"You are efficient at arranging your inventory in general.  This makes it much easier to carry that little extra you've always needed.",
	"You do extra damage with fire-based weapons, and enemies always seem to die in the most painful fiery fashion.",
	"You are quick at recovering from being knocked down.",
	"You are an adept salesperson.  With this Perk you gain +40% towards your Barter skill.",
	"You are much less likely to be knocked down in combat.",
	"The blood of a thief runs through your veins.  Luck/50 chance for no timeout when failing to steal.  A well rounded thief is alive thief.",
	"You can wield weapons much larger than normally allowed. You gain a +2 to your strength for the purposes of Strength checks when trying to wield weaponry.",
	"You have received the Vault City medical training.",
	"You can sling bull with the best of them.",
	"The good thing is that everyone around you has more critical failures in combat. The bad thing is that you do too!",
	"Forget about limbs crippling, blindness, knock-downs! Your skeleton and titanium-alloy vital organs will not break even if a tank crosses you! All critical hits ignored.",
	"You have large legs, you are able to shrug off leg shots that would floor others.",
	"They will have to pry your gun from your cold dead hands. You suffer fewer weapon drops and arm cripples.",
	"You are as tough as they come. Critical hits just don’t seem to affect you as much as they do others.",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	" ",
	"You are able to spot the vulnerable points in enemies. You gain 10% critical chance.",
	"You are able to hit your target with unerring accuracy. Helmets are no protection against you! ",
	"You are able to reload your weapon very quickly. It only takes you 1 AP.",
	"You cover your target in bullets... one of them is bound to find a hole. You ignore armour’s Critical Modifier.",
	"Your advanced training in firearms and other ranged weapons has made you even more deadly in ranged combat than those with a basic training. You do +3 points of damage with ranged weapons {",
	"You have learnt to harness your extra energy and in battle you are a blur. You double your bonus AC gained from your AG.",
	"You have the knowledge of how to skin geckos properly in order to get their pelts.",
	"You have gained +10% resistance to both poison and radiation.",
	"You have inherent protection against physical attacks.",
	"You have extra inherent protection against physical attacks.",
	"You have inherent protection against energy attacks.",
	"You have extra inherent protection against energy attacks.",
	"If both of your item slots are empty, you get a +40 bonus to your Armor Class.",
	"You are even less likely to be hit in combat if you have this Perk. You gain a +40 to your Armor Class.",
	"When you are even tougher, you take even less damage. You gain +10% to your Damage Resistance and +3 to your Damage Threshold.",
	"The healing of bodies comes easier to you with this Perk. This Perk heals 20-40 additional hit points when using the First Aid",
	"You are able to bring people back from the brink of death. You can heal people even when they are Weakened.",
	" ",
	" ",
	"Mastery in unarmed combat has given you the edge when it comes to damage.  You cause +15% critical chance with hand-to-hand and melee attacks.",
	"You cut an intimidating figure and people cower when you are near. Opponents have a 50% chance of missing you when in an adjacent square.",
	"You are an expert at punching through the weak spots in armor. The Critical Modifier value of any armor is reduced by 50% ",
	"The critical hits you cause in hand to hand combat are more devastating. You gain a +25 bonus on the critical hit table. This does not affect the chance to cause a critical hit.",
	"This perk gives you an additional +1 to Strength (up to 10), for purposes of determining range with thrown weapons only. This Perk will exceed a weapon's maximum range.",
	" ",
	" ",
	"Your raw sexual magnetism affects your relationship with the opposite sex in your favor.  All reputations in such relationships are better for 250 points.",
	" ",
	" ",
	" ",
	"Your intuitive understanding of the inner mechanism of Stealth Boys allows you to use them for twice as long.",
	"You are an expert at rescuing equipment which is on the verge of falling apart.  All items with a condition of below 15% count as 15% when being repaired.",
	"You're the kind of a person who always finds spare screws after dismantling a clock and putting it back together.  You recycle twice the usual number of base resources whenever dismantling an item.",
	" ",
	" ",
	"You are exceptionally skilled when it comes to search for valuables long forgotten.  You find more wealth in lockers scattered in the encounters.",
	"",
	"Like Rasputin, it takes a lot to finally finish you off.  Your health points can drop to twice the negative value before you finally die.",
	"It is designed to provide increased damage tolerance by bolstering the user's skin cells with iron.",
	"It is designed to enhance the muscle mass of the person it's installed in by acting as an automatic version of steroids, forcing the body to make a large amount of muscle mass.",
	"It is designed to improve eyesight of the person it's installed in by acting as a pair of sight enhancing glasses, sharpening the view of the user of the implant.",
	"It is designed to improve sensory receptors in the body that detect potentially damaging stimuli (such as excess pressure or heat) and send the nerve signals to the brain and spinal cord.",
	"It is designed to compute possible reactions of other human beings and suggesting actions to it's user.",	
	"It is designed to improve logical thinking of the person it's installed in by calculating possible outcome, thus helping in solving problems and making the best decision.",
	"It is designed to boost the reflex action of the recipient by conducting the electric current in the nervous system and sending it to the area where it needs to go to.",
	"It is designed to aid the person it's installed in by quickly calculating the chances of every single possible thing that can happen, allowing the user to make the best choice in any situation."
);

# FOGAME.MSG :: 105701 - 105791 (step 10)
$lang_proffesions = array(
	"Profession: Armorer",
	"Profession: Gunsmith (Small Guns)",
	"Profession: Gunsmith (Big Guns)",
	"Profession: Energy Expert",
	"Profession: Demolition Expert",
	"Profession: Doctor",
	"Profession: Mordino\'s Druggist",
	"Profession: Thief",
	"Profession: Librarian",
	"Profession: Scout"
);

# FOGAME.MSG :: 105702 - 105792 (step 10)
$lang_proffesions_descr = array(
	"Your everyday outfit just don\'t cut it. Making your personal, straight-from-the-workbench protective gear is something you live for.",
	"You feel like your life would make no sense without pistols, rifles and ammo. You use each and every chance to make something that can shoot or be shot at.",
	"You feel like your life would make no sense without big guns and ammo. You use each and every chance to make something that can make a big boom.",
	"Your life has one purpose only: to master the energy flows and storages. Good thing you can use your experience even when fiddling with the energy weapons.",
	"If it ain\'t go boom, it has no meaning to you. You\'re obsessed with explosions, really.",
	"Helping people when they are injured or ill is all you care about. Noble profession, indeed.",
	"Your chemistic talents were recognized by the Mordinos, and now you\'re one of them. You\'ve got everything you want, as long as you keep the stuff coming.",
	"The gap between poor masses and a few wealthy persons in this world is successfully bridged by you. You take from the rich and give to the poor - yourself.",
	"Librarian",
	"There\'s no rathole in this world you are not going to find. The question is only how much time you\'re going to need for that."
);

# FOGAME.MSG :: 6000 - 6002
$lang_karma_info = array(
	"Karma",
	": %d (%s)",
	"This is a ranged stat that represents your general reputation. The higher the number, the better known and respected you are. If your rep is negative, you are hated by some for your evil actions."
);

# FOGAME.MSG :: 104801 - 104971 (step 10)
$lang_karma = array(
	"Berserker",
	"Champion",
	"Childkiller",
	"Sexpert",
	"Prizefighter",
	"Gigolo",
	"Grave Digger",
	"Married",
	"Porn Star",
	"Slaver",
	"Virgin of the Wastes",
	"Made Man: Salvatore",
	"Made Man: Bishop",
	"Made Man: Mordino",
	"Made Man: Wright",
	"Separated",
	"Ranger"
);

# FOGAME.MSG :: 104802 - 104972 (step 10)
$lang_karma_descr = array(
	"You have killed a large number of people. This is generally not a good thing to get known for. People from the wrong side of the track will like you a little more, however.",
	"Your actions have revealed you to be a champion of the people. Your war against evil and villainy is widely known. Honorable people will respect you better.",
	"You have killed children, the youth of the wasteland. This is considered to be a really bad thing. You evil, evil person.",
	"You know sex. You know foreplay. You know how to please a member of the opposite sex and leave them hungry for more.",
	"You are the heavyweight champion of Northern California. You have gained fame, respect, the love of thousands... and a bonus to your toughness and unarmed skill.",
	"Let\'s be honest: You sleep with anything that walks on two legs. Sometimes, you\'re not even that discriminating.",
	"\"They\'re dead, they don\'t care,\" has become your motto. Digging up the remains of others is more than a hobby for you.",
	"You got hitched. Hey, it\'s your problem, not ours.",
	"You are a big, bright, shining star. Your sexual exploits are well-known throughout New Reno.",
	"You have been marked as a member of the Slaver\'s Guild. The tattoo on your forehead makes your profession evident to everyone you meet.",
	"You really need to get out more. Your sexual exploits have been...well, two dimensional.",
	"You are a \"Made Man\" of the Salvatore Family. You are well-known, well-respected, and look great in a fedora.",
	"You are a \"Made Man\" of the Bishop Family. You are well-known, well-respected, and look great in a fedora.",
	"You are a \"Made Man\" of the Mordino Family. You are well-known, well-respected, and look great in a fedora.",
	"You are a \"Made Man\" of the Wright Family. You are well-known, well-respected, and look great in a fedora.",
	"Your spouse is no longer with you. I hope you\'re happy.",
	"You hate slaver and your life is dedicated to free the slaves!"
);

# FOGAME.MSG :: 6900, 104701, 104711, 104721, 104731, 104741, 104751, 104761, 104771, 104781
$lang_addictions = array(
	"Addictions",
	"Nuka-Cola Addiction",
	"Buffout Addiction",
	"Mentats Addiction",
	"Psycho Addiction",
	"Radaway Addiction",
	"Jet Addiction",
	"Tragic Addiction",
	"Cigarettes Addiction",
	"Alcoholism"
);

# FOGAME.MSG :: 6901, 104702, 104712, 104722, 104732, 104742, 104752, 104762
$lang_addictions_descr = array(
	"Things you have become addicted to.",
	"You crave another Nuka-Cola.",
	"You\'ve got the shakes.",
	"You feel groggy.",
	"You feel light-headed.",
	"You feel nauseous.",
	"Everything is moving so slowly... you need to get some more Jet, right NOW!",
	"You feel a burning desire to open another box of Tragic cards.",
	"You crave for another cigarette.",
	"You never have enough."
);

# FOGAME.MSG :: 6550 - 6556
$lang_reputation_rating = array(
	"Everyone in this area would like to be you. You\'re the toast-of-the-town and are held up as a shining example of all that a person can be.",
	"People wave, and greet you, wherever you go in this area. Everyone has heard talk of you, and they like what they\'ve heard.",
	"Although, you\'re not greeted with open arms, most people in this area will at least nod in acknowledgment when you meet. You fit in as well as most.",
	"Though normally suspicious of strangers, the people of this area haven\'t made up their minds about you yet.",
	"You\'re just another out-of-towner in this area. Probably up to no good.",
	"You\'ve proven to the people in this area that their initial distrust was well founded. People in this area look at you and mutter to one another when you come near. They know you\'re up to no good.",
	"Staring and muttering, some cross the street to avoid walking near you, while others spit and turn away when you come near. Everyone knows that you\'re one of the worst things that have ever slithered into this area."
);

# FOGAME.MSG :: 106021 - 106911 (step 10)
# !!!Need handfix!!!
$lang_factions = array(
	"Brotherhood of steel",
	"The Enclave",
	"The Unity",
	"New California Republic",
	"Citizens of Vault City",
	"Raiders",
	"Mordino Family",
	"Slaver's Guild",
	"The Slags",
	"Kokoweef Mine",
	"Morningstar Mine",
	"Broken Hills Humans",
	"Broken Hills Mutants",
	"Wright Family",
	"Bishop Family",
	"Salvatore Family",
	"NCR Rangers",
	"Vortis' Slavers",
	"Communists",
	"Tanker Vagrants",
	"Crypts",
	"Fools",
	"Hub Criminals",
	"Crimson Caravans",
	"Far Go Traders",
	"Water Merchants",
	"The Heights Residents",
	"Regulators",
	"LA Scavengers",
	"Gun Runners",
	"Followers of the Apocalypse",
	"Bounty Hunters",
	"Free Traders",
	"Guttersnipes",
	"FLC",
	"Slaves",
	"Lara's Gang",
	"Children of the Cathedral",
	"New Reno Sex Workers",
	"Hubologist",
	"Cathedral of the Lost",
	"New Reno Corsican Brothers",
	"Not recognized: 44",
	"Not recognized: 45",
	"Not recognized: 46",
	"Not recognized: 47",
	"Not recognized: 48",
	"Not recognized: 49",
	"Not recognized: 50",
	"Not recognized: 51",
	"Not recognized: 52",
	"Not recognized: 53",
	"Not recognized: 54",
	"Not recognized: 55",
	"Not recognized: 56",
	"Not recognized: 57",
	"Not recognized: 58",
	"Not recognized: 59",
	"Not recognized: 60",
	"Not recognized: 61",
	"Not recognized: 62",
	"Not recognized: 63",
	"Not recognized: 64",
	"Not recognized: 65",
	"Not recognized: 66",
	"Not recognized: 67",
	"Not recognized: 68",
	"Not recognized: 69",
	"Not recognized: 70",
	"Not recognized: 71",
	"Not recognized: 72",
	"Not recognized: 73",
	"Not recognized: 74",
	"Not recognized: 75",
	"Not recognized: 76",
	"Not recognized: 77",
	"Not recognized: 78",
	"Not recognized: 79",
	"Klamath Citizens",
	"Den Citizens",
	"Modoc Citizens",
	"Courtyard Citizens",
	"Gecko Ghouls",
	"Redding Citizens",
	"Broken Hills Ghouls",
	"Population of New Reno",
	"Necropolis Ghouls",
	"Junktown Citizens",
	"Hub Citizens",
	"LA Citizens",
	"Las Vegas Citizens",
	"Nuka Cola Bottlers",
	"Carpenter & Steel Inc.",
	"Wind of War Soldiers",
	"NCR Army",
	"Mutants from Mariposa",
	"Area 51 Secure System",
	"Army of Hawthorne",
	"Salt Lake Citizens",
	"Cheyenne Farmers",
	"Cheyenne Citizens",
	"Bertolini Family",
	"Luciano Family",
	"Thompson Family",
	"Stryker Family",
	"Las Vegas Slavers",
	"Arroyo Tribals",
	"Bridgeport Vendors",
	"Vault-X Citizens",
	"Slavers from Vault",
	"Anticheat Police"
);

# FOGAME.MSG :: 6405, 6500 - 6506
$lang_reputation = array(
	"Reputation",
	"Idolized",
	"Liked",
	"Accepted",
	"Neutral",
	"Antipathy",
	"Hated",
	"Vilified"
);

# FOGAME.MSG :: 6406, 6550 - 6556
$lang_reputation_descr = array(
	"Represents your reputation for a particular location.",
	"Everyone in this area would like to be you. You\'re the toast-of-the-town and are held up as a shining example of all that a person can be.",
	"People wave, and greet you, wherever you go in this area. Everyone has heard talk of you, and they like what they\'ve heard.",
	"Although, you\'re not greeted with open arms, most people in this area will at least nod in acknowledgment when you meet. You fit in as well as most.",
	"Though normally suspicious of strangers, the people of this area haven\'t made up their minds about you yet.",
	"You\'re just another out-of-towner in this area. Probably up to no good.",
	"You\'ve proven to the people in this area that their initial distrust was well founded. People in this area look at you and mutter to one another when you come near. They know you\'re up to no good.",
	"Staring and muttering, some cross the street to avoid walking near you, while others spit and turn away when you come near. Everyone knows that you\'re one of the worst things that have ever slithered into this area."
);

# FOGAME.MSG :: 102601 - 102851 (step 10)
$lang_kills = array(
	"Men",
	"Women",
	"Children",
	"Super Mutants",
	"Ghouls",
	"Brahmin",
	"Radscorpions",
	"Rats",
	"Floaters",
	"Centaurs",
	"Robots",
	"Dogs",
	"Manti",
	"DeathClaws",
	"Plants",
	"Geckos",
	"Aliens",
	"Giant Ants",
	"Big Bad Boss",
	"Desert Stalkers",
	"Venus Man Traps",
	"Rad Toads",
	"Thornslingers",
	"Pashtshuurs",
	"Players",
	"Spiders"
);

# FOGAME.MSG :: 102602 - 102852 (step 10)
$lang_kills_descr = array(
	"This line shows the number of male humans you have killed during the course of your adventures.",
	"This line shows the number of female humans you have killed during the course of your adventures.",
	"This line shows the number of young human children you have killed during the course of your adventures.  You cad.",
	"The number of Super Mutants you have slain during the course of your adventures.",
	"This line shows the number of male and female ghoul mutants you have killed during the course of your adventures.",
	"This line shows the number of Brahmin (mutated cows) you have chopped up during your travels.",
	"The number of mutated Radscorpions that you have put to death during your adventure.",
	"The number of rats you have killed.  Includes all members of the rat family.",
	"This is the number of mutant Floaters that you have put to death.",
	"Your tally of dead mutant Centaurs.",
	"This is the number of robots that you have destroyed or dismantled.",
	"The total number of dogs that you have sent to the great kennel in the sky.",
	"This line shows the total number of dead Manti, or large mutated mantis-like insects, that you have squashed so far.",
	"This line shows that you have slain the Deathclaw, and any of his spawn.",
	"This line shows the number of plants you have weeded out of the world.",
	"The number of cute lizards you have wiped off the face of the planet.",
	"A count of alien things slain by your hand.",
	"The number of insectoids that you have exterminated in the wasteland.",
	"The count of genetically-engineered total homicidal maniac cyborg bodyguards you have wasted.",
	"This line shows the number of Desert Stalker (mutated ant lions) you have killed during the course of your adventures.",
	"This line shows the number of plants you have weeded out of the world.",
	"This line shows the number of Rad Toads that you have put to death during your adventure.",
	"This line shows the number of plants you have weeded out of the world.",
	"The number of terrifying monsters you have killed during your adventure.",
	"This line shows the number of players you have killed during the course of your adventures.",
	"The number of terrifying monsters you have killed during your adventure."
);

?>